# Generated by Django 5.0.3 on 2024-11-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='isPublic',
            field=models.BooleanField(default=False),
        ),
    ]
