# Generated by Django 5.0.3 on 2024-11-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_userpost_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
