# Generated by Django 5.0.3 on 2024-11-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_userpost_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='userpost',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
