# Generated by Django 5.0.3 on 2024-11-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_userpost_profile_picture_userpost_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
