# Generated by Django 5.0.3 on 2024-11-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_userpost_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='vehicle',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
